bug fix for unclosed token
Fatal Exception java.lang.RuntimeException
Unable to stop activity
{com.buuuk.st/com.buuuk.st.activity.HomeActivity}:
android.database.sqlite.SQLiteException: unable to close due to
unfinalised statements